global:
  params:
    p1: 5432
    p2: 2345
spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: refresh
